//
//  HomeInteractor.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation


protocol HomeBusinessLogic {
    func getMovies(request: Home.FetchMovieScene.Request)
    func getMoviesSearch(query: String)
}

class HomeInteractor: Interactor, HomeBusinessLogic {
    
    lazy var presenter: HomePresentationLogic = {
        return self._presenter as! HomePresentationLogic
    }()
    let worker = HomeWorker()
    
    func getMovies(request: Home.FetchMovieScene.Request) {
        self.worker.getMovies(completeUrl: request.completeUrl) { response in
            self.presenter.presentMovies(section: request.type, response: response)
        }
    }

    func getMoviesSearch(query: String) {
        self.worker.getMoviesSearch(completeUrl: query) { response in
            self.presenter.presentMoviesSearch(response: response)
        }
    }
    
}
