//
//  HomeInteractor.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation


protocol HomeBusinessLogic {
    func getMovies(request: Home.FetchMovieScene.Request)
}

class HomeInteractor: Interactor, HomeBusinessLogic {
    
    lazy var presenter: HomePresentationLogic = {
        return self._presenter as! HomePresentationLogic
    }()
    let worker = HomeWorker()
    
    func getMovies(request: Home.FetchMovieScene.Request) {
        self.worker.getMovies() { response in
            self.presenter.presentMoviesAndSeries(response: response)
        }
    }
    
}
