//
//  HomePresenter.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import UIKit

protocol HomePresentationLogic {
    func presentMovies(section: Home.SectionsTitle, response: [ResultsMovies])
    func presentMoviesSearch(response: [ResultsMovies])
}

class HomePresenter: Presenter, HomePresentationLogic {
    
    lazy var view: HomeDisplayLogic = {
        return self._view as! HomeDisplayLogic
    }()
    
    func presentMovies(section: Home.SectionsTitle, response: [ResultsMovies]) {
        let viewModel = Home.FetchMovieScene.ViewModel(section: section, playingMovies: response)
        view.displayMoviesAndSeries(viewModel: viewModel)
    }

    func presentMoviesSearch(response: [ResultsMovies]) {
        view.displayMoviesSearch(response: response)
    }
}
