//
//  HomeWorker.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import UIKit
import RxSwift

class HomeWorker {

    private let disposeBag = DisposeBag()
    
    func getMovies(completion: @escaping ([ResultsMovies]) -> Void) {
        let request =  APIRequest()
        request.baseURL = URL(string: APIStrings.mainURL + "movie/popular?api_key=16ee70222ce1112fdee882ae05f0055f")!
        let result : Observable<[ResultsMovies]> = APIService.apiCalling.getMovies(apiRequest: request)
        result.subscribe(
            onNext: { result in
                completion(result)
            },
            onError: { error in
                print(error.localizedDescription)
            },
            onCompleted: {
                print("Completed event.")
            }).disposed(by: disposeBag)
    }

    
}
