//
//  HomeWorker.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import UIKit
import RxSwift

class HomeWorker {

    private let disposeBag = DisposeBag()
    
    func getMovies(completeUrl: String, completion: @escaping ([ResultsMovies]) -> Void) {
        let request =  APIRequest()
        request.completeUrl = completeUrl
        let result : Observable<[ResultsMovies]> = APIService.apiCalling.getMovies(apiRequest: request)
        result.subscribe(
            onNext: { result in
                completion(result)
            },
            onError: { error in
                print(error.localizedDescription)
            }).disposed(by: disposeBag)
    }

    func getMoviesSearch(completeUrl: String, completion: @escaping ([ResultsMovies]) -> Void) {
        let request =  APIRequest()
        request.completeUrl = completeUrl
        let result : Observable<[ResultsMovies]> = APIService.apiCalling.getMoviesSearch(apiRequest: request)
        result.subscribe(
            onNext: { result in
                completion(result)
            },
            onError: { error in
                print(error.localizedDescription)
            }).disposed(by: disposeBag)
    }

    
}
