//
//  HomeViewController.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import Foundation
import UIKit
import RxSwift
import RxCocoa
import RxDataSources
import SDWebImage

protocol HomeDisplayLogic: View {
    func displayMovies(viewModel: Home.FetchMovieScene.ViewModel)
    func displayMoviesSearch(response: [ResultsMovies])
}

class HomeViewController: UIViewController {
    
    // MARK: - Variables
    
    lazy var interactor: HomeBusinessLogic = {
        return self._interactor as! HomeBusinessLogic
    }()
    lazy var router: HomeRoutingLogic = {
        return self._router as! HomeRoutingLogic
    }()

    private var moviesCollectionView: UICollectionView = {
        let collectionView = UICollectionView(frame: CGRect.zero, collectionViewLayout: UICollectionViewFlowLayout.init())
        return collectionView
    }()

    private let searchController: UISearchController = {
        let searchController = UISearchController(searchResultsController: nil)
        searchController.searchBar.placeholder = "Buscar Pelicula"
        searchController.searchBar.backgroundColor = .black
        return searchController
    }()

    private let searchTableView = UITableView()
    private let searchCellIdentifier = "searchCellIdentifier"

    var allItems = BehaviorRelay<[AllMovies]>(value: [AllMovies()])
    private var bag = DisposeBag()
    var searchItems = BehaviorRelay<[ResultsMovies]>(value: [ResultsMovies()])

    let dataSource = RxCollectionViewSectionedReloadDataSource<AllMovies>(configureCell: {
        _, cv, ip, item in
        let cell: MoviesCollectionViewCell = cv.dequeueReusableCell(withReuseIdentifier: "cell", for: ip) as! MoviesCollectionViewCell
        cell.movie = item
        return cell
    }, configureSupplementaryView: {ds, cv, _, ip in
        let header = cv.dequeueReusableSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "cellHeader", for: ip) as! ContentCollectionViewHeader
        header.sectionNameLabel.text = ds.sectionModels[ip.section].name
        return header
    })

    
    // MARK: - Object Lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - View Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        self.showMoviews()
        self.displaySearchMovies()

        if Reachability.isConnectedToNetwork() {
            self.interactor.getMovies(request: Home.FetchMovieScene.Request(type: .popular,
                                                                            completeUrl: "movie/popular"))
            self.interactor.getMovies(request: Home.FetchMovieScene.Request(type: .topRanked,
                                                                            completeUrl: "movie/top_rated"))
            self.interactor.getMovies(request: Home.FetchMovieScene.Request(type: .upcoming,
                                                                            completeUrl: "movie/upcoming"))
        } else {
            self.interactor.getMoviesOffline(section: Home.SectionsTitle.popular.rawValue)
            self.interactor.getMoviesOffline(section: Home.SectionsTitle.topRanked.rawValue)
            self.interactor.getMoviesOffline(section: Home.SectionsTitle.upcoming.rawValue)
        }

        searchController.searchBar
            .rx.text
            .orEmpty
            .debounce(.milliseconds(500), scheduler: MainScheduler.instance)
            .subscribe(onNext: { [unowned self] query in
                if query.count > 2 {
                    if Reachability.isConnectedToNetwork() {
                        let realQuery = query.replacingOccurrences(of: " ", with: "%20")
                        self.interactor.getMoviesSearch(query: "search/movie?query=\(realQuery)",
                                                        isOnline: true)
                    } else {
                        self.interactor.getMoviesSearch(query: query,
                                                        isOnline: false)
                    }
                } else {
                    DispatchQueue.main.async {
                        self.searchTableView.isHidden = true
                    }
                }
            })
            .disposed(by: bag)
    }
    
    // MARK: - Configurators
    
    fileprivate func setup() {
        self.setup(
            interactor: HomeInteractor(),
            presenter: HomePresenter(),
            router: HomeRouter())
    }
    
    // MARK: - Private

    private func setupUI() {
        moviesCollectionView.backgroundColor = .black
        moviesCollectionView.register(MoviesCollectionViewCell.self, forCellWithReuseIdentifier: "cell")
        moviesCollectionView.register(ContentCollectionViewHeader.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "cellHeader")
        moviesCollectionView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(moviesCollectionView)
        searchTableView.register(UITableViewCell.self, forCellReuseIdentifier: searchCellIdentifier)
        searchTableView.translatesAutoresizingMaskIntoConstraints = false
        searchTableView.isHidden = true
        searchTableView.backgroundColor = .black
        view.addSubview(searchTableView)
        NSLayoutConstraint.activate([
            moviesCollectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            moviesCollectionView.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor),
            moviesCollectionView.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor),
            moviesCollectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            searchTableView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            searchTableView.leftAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leftAnchor),
            searchTableView.rightAnchor.constraint(equalTo: view.safeAreaLayoutGuide.rightAnchor),
            searchTableView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
        moviesCollectionView.contentInset.bottom = view.safeAreaInsets.bottom
        searchTableView.contentInset.bottom = view.safeAreaInsets.bottom
        navigationItem.searchController = searchController
        navigationItem.title = "Movies"
        navigationItem.hidesSearchBarWhenScrolling = false
        navigationController?.navigationBar.prefersLargeTitles = true
        
        moviesCollectionView.collectionViewLayout = layout()
    }

    private func layout() -> UICollectionViewLayout {
           return UICollectionViewCompositionalLayout {[weak self] sectionNumber, environment -> NSCollectionLayoutSection? in
               guard let self = self else { return nil }
               return self.createBasicTypeSection()
           }
       }

    private func createBasicTypeSection() -> NSCollectionLayoutSection {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(0.3), heightDimension: .fractionalHeight(0.90))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.contentInsets = .init(top: 10, leading: 5, bottom: 0, trailing: 5)

        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(0.9), heightDimension: .estimated(200))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 3)

        let section = NSCollectionLayoutSection(group: group)
        section.orthogonalScrollingBehavior = .continuous
        section.contentInsets = .init(top: 0, leading: 5, bottom: 0, trailing: 5)
        
        let sectionHeader = self.createSectionHeader()
        section.boundarySupplementaryItems = [sectionHeader]
        
        return section
    }

    private func createSectionHeader() -> NSCollectionLayoutBoundarySupplementaryItem {
        let layoutSectionHeaderSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1), heightDimension: .absolute(30))

        let sectionHeader = NSCollectionLayoutBoundarySupplementaryItem(layoutSize: layoutSectionHeaderSize, elementKind: UICollectionView.elementKindSectionHeader, alignment: .top)
        
        return sectionHeader
    }

    private func showMoviews() {
        self.allItems
            .bind(to: self.moviesCollectionView.rx.items(dataSource: self.dataSource))
            .disposed(by: self.bag)
        self.moviesCollectionView.rx.modelSelected(ResultsMovies.self).subscribe(onNext: {[weak self] model in
            self?.router.showDetailMovie(idMovie: model.id ?? 0)
        }).disposed(by: self.bag)
    }

    private func displaySearchMovies() {
        searchItems.asObservable()
            .bind(to: searchTableView.rx
                .items(cellIdentifier: searchCellIdentifier, cellType: UITableViewCell.self))
        { index, element, cell in
            cell.textLabel?.textColor = .white
            cell.backgroundColor = .black
            cell.textLabel?.text = element.title
        }.disposed(by: self.bag)

        searchTableView.rx.modelSelected(ResultsMovies.self)
            .subscribe(onNext: { [weak self] model in
                self?.router.showDetailMovie(idMovie: model.id ?? 0)
            }).disposed(by: self.bag)
        
        searchTableView.tableFooterView = UIView()
    }
    
    // MARK: - Actions
    
}

extension HomeViewController: HomeDisplayLogic {
    func displayMovies(viewModel: Home.FetchMovieScene.ViewModel) {
        switch viewModel.section {
        case .popular:
            self.allItems.accept([AllMovies(name: viewModel.section.rawValue, movies: viewModel.playingMovies ?? [ResultsMovies]())])
        default:
            self.allItems.add(element: AllMovies(name: viewModel.section.rawValue, movies: viewModel.playingMovies ?? [ResultsMovies]()))
        }
        if Reachability.isConnectedToNetwork() {
            self.interactor.saveCacheMovies(request: viewModel)
        } else {
            if viewModel.playingMovies?.count ?? 0 < 1 {
                DispatchQueue.main.async {
                    Tools.showAlert(title: "Sin conexión",
                                    message: "Para ver el contenido offline es necesario primero ingresar con conexión a internet 🥳", titleForTheAction: "Aceptar", in: self, titleForCancelAction: "") {
                        print("hello Rappi")
                    }
                }
            }
        }
    }

    func displayMoviesSearch(response: [ResultsMovies]) {
        DispatchQueue.main.async {
            self.searchTableView.isHidden = false
            self.searchItems.accept(response)
        }
    }
}
