//
//  HomeRouter.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import UIKit

protocol HomeRoutingLogic {
    func showDetailMovie(idMovie: Int)
}

class HomeRouter: Router, HomeRoutingLogic {
    
    lazy var view: HomeViewController = {
        return self._view as! HomeViewController
    }()
    
    func showDetailMovie(idMovie: Int) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            let detailMovieViewController = MovieDetailViewController()

            guard var destination = detailMovieViewController.router?.dataStore else {
                return
            }
            self.passDataToDetail(source: idMovie, destination: &destination)
            self.navigateToSomewhere(source: self.view, destination: detailMovieViewController)
        }
        
    }

    // MARK: - Helpers
    private func passDataToDetail(source: Int, destination: inout MovieDetailDataStore) {
        destination.idMovie = source
    }
    
    func navigateToSomewhere(source: HomeViewController, destination: MovieDetailViewController) {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: false)
    }
}
