//
//  HomeRouter.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 11/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import UIKit

protocol HomeRoutingLogic {
    func routeToSomewhere()
}

class HomeRouter: Router, HomeRoutingLogic {
    
    lazy var view: HomeViewController = {
        return self._view as! HomeViewController
    }()
    
    func routeToSomewhere() {
        
    }
    
}
