//
//  MovieDetailRouter.swift
//  test-rappi-movies
//
//  Created by Sergio Zorrilla Arellano on 15/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the iOS team Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//

import UIKit

protocol MovieDetailRoutingLogic {
}

protocol MovieDetailDataGet {
    var dataStore: MovieDetailDataStore? { get }
}

class MovieDetailRouter: Router, MovieDetailRoutingLogic, MovieDetailDataGet {
    
    lazy var view: MovieDetailViewController = {
        return self._view as! MovieDetailViewController
    }()

    var dataStore: MovieDetailDataStore?

}
